[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"

[".oh-my-zsh/custom/plugins/autoupdate"]
    type = "git-repo"
    url = "https://github.com/tamcore/autoupdate-oh-my-zsh-plugins.git"

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
[".config/hypr/themes/catppuccin_machiato.conf"]
    type="file"
    url="https://raw.githubusercontent.com/catppuccin/hyprland/main/themes/macchiato.conf"
    refreshPeriod="168h"
